server:
  port: 5000
spring:
  h2:
    console:
      enabled: on
  security:
    user:
      password: 123
      name: user
  datasource:
    url: jdbc:h2:file:./data/TimeManagementDB;NON_KEYWORDS=USER;
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
